# Game Window and Display Settings
WIDTH = 800
HEIGHT = 600
FPS = 60
BG_COLOR = (50, 50, 50)
GAME_BOARD_WIDTH = 800  # Fixed game area dimensions
GAME_BOARD_HEIGHT = 600
BORDER_COLOR = (255, 255, 0)  # Yellow for border visibility
BORDER_THICKNESS = 4  # Thickness of border line

# Gameplay Constants
INITIAL_LIVES = 10
INITIAL_MONEY = 100

# Tower Settings
TOWER_COST = 100
TOWER_UPGRADE_COST_BASE = 50
TOWER_UPGRADE_COST_INCREASE = 50
TOWER_MAX_LEVEL = 3
TOWER_BASE_RANGE = 150
TOWER_BASE_COOLDOWN = 30
TOWER_BASE_DAMAGE = 20
TOWER_RANGE_INCREASE = 25
TOWER_DAMAGE_INCREASE = 10
TOWER_COOLDOWN_DECREASE = 5

# Enemy Rewards
ENEMY_REWARD_BASIC = 10
ENEMY_REWARD_FAST = 20
ENEMY_REWARD_STRONG = 15